language: node_js
sudo: false
dist: xenial

node_js:
  - "11"
  - "10"
  - "8"

cache:
  directories:
    - node_modules

services:
  - redis-server

script:
  - npm test

jobs:
  include:
    - stage: E2E
      node_js: "11"
      script: npm run cypress:ci

after_success:
  - npm run coverall
